# Generated by Django 4.0.2 on 2022-04-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defualt.jpg', upload_to='profile_pics'),
        ),
    ]
